# Generated by Django 6.0.3 on 2026-03-27 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("nature", "Nature"),
                            ("history", "History"),
                            ("food", "Food"),
                            ("active", "Active"),
                            ("photo", "Photo Spots"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("almaty", "Almaty"),
                            ("astana", "Astana"),
                            ("shymkent", "Shymkent"),
                            ("turkestan", "Turkestan"),
                            ("aktau", "Aktau"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("season_best", models.CharField(max_length=50)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("duration_days", models.IntegerField()),
                (
                    "budget_level",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("mid", "Mid-range"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to="travel.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price_level",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("mid", "Mid-range"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("open_hours", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("rating", models.FloatField(default=0.0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="travel.category",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="travel.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("transport_note", models.CharField(blank=True, max_length=300)),
                (
                    "day_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="travel.itinerary",
                    ),
                ),
                (
                    "places",
                    models.ManyToManyField(
                        blank=True, related_name="days", to="travel.place"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("visited_date", models.DateField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="travel.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="travel.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "place")},
            },
        ),
    ]
