# Generated by Django 6.0.3 on 2026-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="best_season",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="place",
            name="duration_hours",
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name="place",
            name="is_indoor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="price_tenge",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("nature", "Nature"),
                    ("history", "History"),
                    ("food", "Food"),
                    ("active", "Active"),
                    ("photo", "Photo Spots"),
                    ("culture", "Culture"),
                    ("nightlife", "Nightlife"),
                    ("shopping", "Shopping"),
                    ("family", "Family"),
                    ("lifestyle", "Lifestyle"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="region",
            field=models.CharField(max_length=100),
        ),
    ]
