# Generated by Django 6.0.4 on 2026-04-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="photo_credit",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="place",
            name="photo_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
