# Generated by Django 6.0.4 on 2026-04-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_place_photo_credit_place_photo_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryDayPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.itineraryday",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.place"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("day", "place")},
            },
        ),
    ]
