# Generated by Django 6.0.4 on 2026-04-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_itinerarydayplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("concert", "🎵 Концерт"),
                            ("theatre", "🎭 Театр"),
                            ("masterclass", "🎨 Мастер-класс"),
                            ("food", "🍽️ Гастро"),
                            ("sport", "🏃 Спорт"),
                            ("kids", "👶 Детям"),
                            ("exhibition", "🖼️ Выставка"),
                            ("party", "🎉 Вечеринка"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("price_from", models.IntegerField(default=0)),
                ("ticket_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_sponsored", models.BooleanField(default=False)),
                (
                    "sponsor_label",
                    models.CharField(blank=True, default="Партнёр", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="travel.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_sponsored", "date", "time"],
            },
        ),
    ]
