# Generated by Django 6.0.4 on 2026-04-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itineraryday",
            name="places",
            field=models.ManyToManyField(
                blank=True,
                related_name="days",
                through="travel.ItineraryDayPlace",
                to="travel.place",
            ),
        ),
    ]
